version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
  
  # Tambahkan service lain jika diperlukan
  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"